[package]
name = "verdigris-ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.3.0", default-features = false, features = [
  "serde",
] }
stylist = "0.12.0"
styled = { path = "../styled" }
color-art = "0.3.1"
anyhow = "1.0.71"