[package]
name = "verdigris-ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.2.4", default-features = false, features = [
  "serde",
] }
csscolorparser = "0.6.2"
stylist = "0.12.0"
styled = "0.1.36"
rgb = "0.8.36"